import GraphicDesignImg from "../assets/topCourses/GraphicDesign.png";
import UiUxImg from "../assets/topCourses/UIUX.png";
import MernImg from "../assets/topCourses/Mern.png";
import DigitalMarketing from "../assets/topCourses/DigitalMarketing.png";
import WordPressImg from "../assets/topCourses/WordPress.png";
import ReactImg from "../assets/topCourses/React.png";

export const TopCoursesData = [
  {
    id: 1,
    title: "Graphic Design Masterclass",
    instructor: "Saifur Rahman",
    image: GraphicDesignImg,
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 2,
    title: "UI-UX Design",
    instructor: "Saifur Rahman",
    image: UiUxImg,
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 3,
    title: "MERN Stack Development",
    instructor: "Saifur Rahman",
    image: MernImg,
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 4,
    title: "Digital Marketing Specialist",
    instructor: "Saifur Rahman",
    image: DigitalMarketing,
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 5,
    title: "WordPress Development",
    instructor: "Saifur Rahman",
    image: WordPressImg,
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 6,
    title: "Development With React",
    instructor: "Saifur Rahman",
    image: ReactImg,
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
];
