export const TopCoursesData = [
  {
    id: 1,
    title: "Graphic Design Masterclass",
    instructor: "Saifur Rahman",
    image: "",
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 2,
    title: "UI-UX Design",
    instructor: "Saifur Rahman",
    image: "",
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 3,
    title: "MERN Stack Development",
    instructor: "Saifur Rahman",
    image: "",
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 4,
    title: "Digital Marketing Specialist",
    instructor: "Saifur Rahman",
    image: "",
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 5,
    title: "WordPress Development",
    instructor: "Saifur Rahman",
    image: "",
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
  {
    id: 6,
    title: "Development With React",
    instructor: "Saifur Rahman",
    image: "",
    rating: 4.9,
    reviews: 560,
    price: 99,
    orginalPrice: 150,
    seatsLeft: 20,
    daysLeft: 72,
    batchNo: "NSL-GD2509",
  },
];
